version: '3.0'

services:
  database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
  web:
    build: ./
    ports:
      - 8181:8181
    depends_on:
      - database
    environment:
      PORT: 8181
volumes:
  database-data:
